// Loading Stuff
export const REQUEST_MADE = 'REQUEST_MADE'
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED'

//Query to instance Fetching
export const FETCH_STARTED_QUERY = "FETCH_STARTED_QUERY"
export const FETCH_FULFILLED_QUERY = "FETCH_FULFILLED_QUERY"
export const FETCH_FAILED_QUERY = "FETCH_FAILED_QUERY"

//Facets Fetching
export const FETCH_STARTED_FACETS = "FETCH_STARTED_FACETS"
export const FETCH_FULFILLED_FACETS = "FETCH_FULFILLED_FACETS"
export const FETCH_FAILED_FACETS = "FETCH_FAILED_FACETS"
export const FACETS_NORMALIZED = "FACETS_NORMALIZED"

//Types Fetching
export const FETCH_STARTED_TYPES = "FETCH_STARTED_TYPES"
export const FETCH_FULTILLED_TYPES = "FETCH_FULTILLED_TYPES"
export const FETCH_FAILED_TYPES = "FETCH_FAILED_TYPES"
export const UPDATE_HOVER_TYPE = "UPDATE_HOVER_TYPE"

//Lightbox controls
export const LIGHTBOX_OPEN = "LIGHTBOX_OPEN"
export const LIGHTBOX_CLOSE = "LIGHTBOX_CLOSE"


