// Instance View
export const FETCH_INSTANCE_STARTED = 'FETCH_INSTANCE_STARTED'
export const FETCH_INSTANCE_FULFILLED = 'FETCH_INSTANCE_FULFILLED'
export const INSTANCE_LINKS_ADDED = 'INSTANCE_LINKS_ADDED'
export const FETCH_INSTANCE_FAILED = 'FETCH_INSTANCE_FAILED'

// List Fetching
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED'

// Loading Stuff
export const REQUEST_MADE = 'REQUEST_MADE'
export const REQUEST_RESOLVED = 'REQUEST_RESOLVED'

//Query to instance Fetching
export const FETCH_QUERY_STARTED = "FETCH_QUERY_STARTED"
export const FETCH_QUERY_FULFILLED = "FETCH_QUERY_FULFILLED"
export const FETCH_QUERY_FAILED = "FETCH_QUERY_FAILED"

//Types Fetching
export const FETCH_TYPES_STARTED = "FETCH_TYPES_STARTED"
export const FETCH_TYPES_FULFILLED = "FETCH_TYPES_FULFILLED"
export const FETCH_TYPES_FAILED = "FETCH_TYPES_FAILED"
export const UPDATE_HOVER_TYPE = "UPDATE_HOVER_TYPE"